Traceback (most recent call last):
  File "otocs_more.py", line 126, in <module>
    otocsfore_all = np.append(otocsfore_all, otocsfore, axis=1)
  File "/group/cmtheory/cnstahl/group/cmtheory/cnstahl/lib/python3.6/site-packages/numpy/lib/function_base.py", line 5166, in append
    return concatenate((arr, values), axis=axis)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
trials: 0 seconds: 1356.8985345363617
trials: 1 seconds: 2698.6990687847137
trials: 2 seconds: 4055.9328968524933
trials: 3 seconds: 5399.902174472809
trials: 4 seconds: 6743.123576879501
trials: 5 seconds: 8084.437410831451
trials: 6 seconds: 9427.944576263428
trials: 7 seconds: 10769.759288072586
trials: 8 seconds: 12114.208684921265
trials: 9 seconds: 13458.812706947327
